apiVersion: v1
kind: ConfigMap
metadata:
  name: pinky-pagerduty
  namespace: default
  labels:
    app.kubernetes.io/name: pinky
data:
  service-name: pinky
  urgency: high
  escalation-timeout-seconds: '300'
  integration-key: PLACEHOLDER
