apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: agentit-cpu-stress
  namespace: default
  labels:
    app.kubernetes.io/name: agentit
spec:
  appinfo:
    appns: default
    applabel: app=agentit
    appkind: deployment
  engineState: active
  chaosServiceAccount: agentit-chaos-sa
  experiments:
  - name: pod-cpu-hog
    spec:
      components:
        env:
        - name: TOTAL_CHAOS_DURATION
          value: '120'
        - name: CPU_CORES
          value: '1'
        - name: CPU_LOAD
          value: '80'
