apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pinky-monitor
  labels:
    app.kubernetes.io/name: pinky
spec:
  selector:
    matchLabels:
      app: pinky
  endpoints:
    - port: http
      path: /metrics
      interval: 30s