apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: pinky-trusted-registries
  namespace: pinky
  labels:
    app.kubernetes.io/name: pinky
spec:
  validationFailureAction: Audit
  rules:
    - name: validate-registries
      match:
        any:
          - resources:
              kinds:
                - Pod
              selector:
                matchLabels:
                  app.kubernetes.io/name: pinky
      validate:
        message: "Images must come from a trusted registry: registry.access.redhat.com, registry.redhat.io, quay.io, or the OpenShift internal registry."
        pattern:
          spec:
            containers:
              - image: "registry.access.redhat.com/*/*| registry.redhat.io/*/*| quay.io/*/*| image-registry.openshift-image-registry.svc*/*"