apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: pinky-vpa
  namespace: pinky
  labels:
    app.kubernetes.io/name: pinky
    agentit.io/l5-proof: "2026-07-16"
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pinky
  updatePolicy:
    updateMode: 'Off'
  resourcePolicy:
    containerPolicies:
    - containerName: pinky
      minAllowed:
        cpu: 50m
        memory: 64Mi
      maxAllowed:
        cpu: 500m
        memory: 512Mi
