apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: agentit-monitor
  labels:
    app.kubernetes.io/name: agentit
    app.kubernetes.io/instance: agentit
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: agentit
spec:
  selector:
    matchLabels:
      app: agentit
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scheme: http
      honorLabels: false
      relabelings:
        - sourceLabels:
            - __meta_kubernetes_pod_name
          targetLabel: pod
        - sourceLabels:
            - __meta_kubernetes_namespace
          targetLabel: namespace
  namespaceSelector:
    matchNames:
      - agentit